name: Run Python Get-Started Mock-up Script

on:
  schedule:
  # Run every weekday at 7:00 AM UTC
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  execute-python-scripts:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
        - name: Checkout code
          uses: actions/checkout@v3

        # Set up Python environment
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        # Install tofupilot package
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install tofupilot openhtf six

        # Set TOFUPILOT_API_KEY and run all Python files in corresponding folder 
        - name: Run Battery-Testing Script
          env: 
            TOFUPILOT_API_KEY: ${{ secrets.GET_STARTED_BATTERY_API_KEY }}
          run: |
            for file in get_started/battery-testing/*.py; do
              python "$file"
            done
        
 
