name: Run Python Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Run the script from GitHub interface
  workflow_dispatch:

jobs:
  execute-python-scripts:
    # Running on both ubuntu and windows
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      TOFUPILOT_API_KEY: ${{ secrets.PRODUCTION_API_KEY}}
      # Forcing Python to run in UTF-8 mode for all steps in this job
      PYTHONUTF8: "1"

    steps:
      # Checking out the repository
      - name: Checking out the repository
        uses: actions/checkout@v3

      - name: Changing code page to UTF-8 (Windows only)
        if: runner.os == 'Windows'
        run: chcp 65001

      # Setting up Python
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Installing dependencies
      - name: Installing dependencies
        shell: bash
        run: |
          -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Running all Python scripts
      - name: Running all Python scripts
        shell: bash
        run: |
          find . -type f -name 'main.py' \
            -not -path '*/venv/*' \
            -not -path '*/.*/*' \
            -print0 | while IFS= read -r -d '' file; do

            directory="$(dirname "$file")"

            if [ -f "$directory/requirements.txt" ]; then
              pip install -r "$directory/requirements.txt"
            fi

            echo "Running files in $directory"

            (
              cd "$directory" || exit
              python main.py
            )
          done
